name: WorldEdit
main: com.sk89q.worldedit.cloudburst.CloudburstWorldEdit
version: "${internalVersion}"
load: STARTUP
api: "2.0"
website: https://intellectualsites.github.io/download/fawe.html
description: Blazingly fast world manipulation for builders, large networks and developers.
authors: [Empire92, MattBDev, IronApollo, dordsor21, NotMyFault]